# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainApplicationV2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 671)
        MainWindow.setStyleSheet("border:0")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setStyleSheet("")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.selectedLogsList = QtWidgets.QListWidget(self.splitter_3)
        self.selectedLogsList.setObjectName("selectedLogsList")
        self.frame_4 = QtWidgets.QFrame(self.splitter_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.availableLogsFilter = QtWidgets.QLineEdit(self.frame_4)
        self.availableLogsFilter.setObjectName("availableLogsFilter")
        self.gridLayout_5.addWidget(self.availableLogsFilter, 0, 0, 1, 1)
        self.availableLogs = QtWidgets.QListWidget(self.frame_4)
        self.availableLogs.setObjectName("availableLogs")
        self.gridLayout_5.addWidget(self.availableLogs, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logDisplayTabs = QtWidgets.QTabWidget(self.frame_5)
        self.logDisplayTabs.setMinimumSize(QtCore.QSize(550, 0))
        self.logDisplayTabs.setStyleSheet("border:0; margin:0")
        self.logDisplayTabs.setObjectName("logDisplayTabs")
        self.gridLayout_2.addWidget(self.logDisplayTabs, 0, 0, 1, 1)
        self.openLogsSearch = QtWidgets.QLineEdit(self.frame_5)
        self.openLogsSearch.setObjectName("openLogsSearch")
        self.gridLayout_2.addWidget(self.openLogsSearch, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.selectedFilters = QtWidgets.QListWidget(self.splitter_2)
        self.selectedFilters.setObjectName("selectedFilters")
        self.frame_6 = QtWidgets.QFrame(self.splitter_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.availableFilterFilter = QtWidgets.QLineEdit(self.frame_6)
        self.availableFilterFilter.setObjectName("availableFilterFilter")
        self.gridLayout_6.addWidget(self.availableFilterFilter, 0, 0, 1, 1)
        self.availableFilters = QtWidgets.QListWidget(self.frame_6)
        self.availableFilters.setObjectName("availableFilters")
        self.gridLayout_6.addWidget(self.availableFilters, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.globalInformation = QtWidgets.QLineEdit(self.centralwidget)
        self.globalInformation.setReadOnly(True)
        self.globalInformation.setObjectName("globalInformation")
        self.verticalLayout.addWidget(self.globalInformation)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Log_Directory = QtWidgets.QAction(MainWindow)
        self.actionAdd_Log_Directory.setObjectName("actionAdd_Log_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_Log_Filter = QtWidgets.QAction(MainWindow)
        self.actionAdd_Log_Filter.setObjectName("actionAdd_Log_Filter")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAdd_Log_Directory)
        self.menuFile.addAction(self.actionAdd_Log_Filter)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.logDisplayTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_Log_Directory.setText(_translate("MainWindow", "Add Log Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_Log_Filter.setText(_translate("MainWindow", "Add Log Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

